[project]
name = "genetic-bitcoin"
authors = ["Genetic Bitcoin Team"]
description = "A decentralized genetic data tracking and analysis platform using Bitcoin's blockchain"
telemetry = false
requirements = []
[contracts.genetic-dna-registry]
path = "contracts/genetic-dna-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
